import { useMemo, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

const sections = [["profile", "Profile"], ["education", "Education"], ["publications", "Publications"], ["experiences", "Experience"], ["skills", "Skills"], ["icons", "Section icons"], ["projects", "Projects"], ["media", "Media"]] as const;
type Section = (typeof sections)[number][0];
type Entry = Record<string, any>;
const emptyItem: Record<Exclude<Section, "profile">, Entry> = {
  education: { institution: "", degree: "", field: "", location: "", startYear: "", endYear: "", description: "", sortOrder: 0 },
  publications: { title: "", venue: "", publicationDate: "", status: "", authors: "", summary: "", details: "", keywords: [], url: "", sortOrder: 0 },
  experiences: { role: "", organization: "", location: "", startDate: "", endDate: "", isCurrent: false, summary: "", highlights: [], sortOrder: 0 },
  skills: { label: "", category: "Robotics Middleware", icon: "ROS", sortOrder: 0 },
  icons: { sectionKey: "education", label: "", url: "", storageKey: "", alt: "", sortOrder: 0 },
  projects: { slug: "", title: "", subtitle: "", summary: "", description: "", status: "", startDate: "", endDate: "", tags: [], tools: [], outcomes: [], featured: false, sortOrder: 0 },
  media: { projectId: 0, url: "", storageKey: "", alt: "", sortOrder: 0 },
};
const labels: Record<string, string> = { name: "Name", professionalTitle: "Professional title", location: "Location", email: "Email", linkedinUrl: "LinkedIn URL", bio: "Bio", institution: "Institution", degree: "Degree", field: "Field", startYear: "Start year", endYear: "End year", description: "Description", sortOrder: "Display order", title: "Title", venue: "Conference / journal", publicationDate: "Publication date", status: "Status", authors: "Authors", url: "File URL", role: "Role", organization: "Organisation", startDate: "Start date", endDate: "End date", summary: "Abstract / summary", details: "Paper details", keywords: "Keywords", highlights: "Highlights", label: "Label", category: "Category", icon: "Icon", slug: "Project slug", subtitle: "Subtitle", tags: "Tags", tools: "Tools", outcomes: "Outcomes", featured: "Feature this project", projectId: "Project", alt: "Accessible description", photoUrl: "Profile photo URL", sectionKey: "Display in section" };
const fields: Record<Section, string[]> = { profile: ["name", "professionalTitle", "location", "email", "linkedinUrl", "bio", "photoUrl"], education: ["institution", "degree", "field", "location", "startYear", "endYear", "description", "sortOrder"], publications: ["title", "venue", "publicationDate", "status", "authors", "summary", "details", "keywords", "url", "sortOrder"], experiences: ["role", "organization", "location", "startDate", "endDate", "isCurrent", "summary", "highlights", "sortOrder"], skills: ["label", "category", "icon", "sortOrder"], icons: ["sectionKey", "label", "url", "alt", "sortOrder"], projects: ["title", "slug", "subtitle", "status", "startDate", "endDate", "summary", "description", "tags", "tools", "outcomes", "featured", "sortOrder"], media: ["projectId", "url", "alt", "sortOrder"] };
function displayTitle(section: Section, item: Entry) { if (section === "profile") return item.name || "Profile"; return item.title || item.role || item.label || item.institution || item.url || "New item"; }

export default function Admin() {
  const { user, loading } = useAuth(); const [active, setActive] = useState<Section>("profile"); const [selected, setSelected] = useState<Entry | null>(null); const utils = trpc.useUtils();
  const content = trpc.portfolio.content.useQuery({ type: active }, { enabled: !!user && user.role === "admin" });
  const projectsForMedia = trpc.portfolio.content.useQuery({ type: "projects" }, { enabled: !!user && user.role === "admin" });
  const allMedia = trpc.portfolio.content.useQuery({ type: "media" }, { enabled: !!user && user.role === "admin" });
  const refresh = async () => { await utils.portfolio.content.invalidate(); await utils.portfolio.public.invalidate(); };
  const save = trpc.portfolio.save.useMutation({ onSuccess: async () => { toast.success("Content saved"); await refresh(); }, onError: (error) => toast.error(error.message) });
  const remove = trpc.portfolio.remove.useMutation({ onSuccess: async () => { toast.success("Item deleted"); setSelected(null); await refresh(); }, onError: (error) => toast.error(error.message) });
  const removeMedia = trpc.portfolio.remove.useMutation({ onSuccess: async () => { toast.success("Image deleted"); await refresh(); }, onError: (error) => toast.error(error.message) });
  const uploadProjectImage = trpc.portfolio.uploadProjectImage.useMutation({ onSuccess: async () => { toast.success("Project image uploaded to storage"); await refresh(); }, onError: (error) => toast.error(error.message) });
  const uploadProfilePhoto = trpc.portfolio.uploadProfilePhoto.useMutation({ onSuccess: async (stored) => { setSelected((current) => ({ ...(current ?? {}), photoUrl: stored.url, photoKey: stored.key })); toast.success("Profile photo uploaded and saved"); await refresh(); }, onError: (error) => toast.error(error.message) });
  const uploadSectionIcon = trpc.portfolio.uploadSectionIcon.useMutation({ onSuccess: (stored) => { setSelected((current) => ({ ...(current ?? {}), url: stored.url, storageKey: stored.key })); toast.success("Icon uploaded. Save this item to publish it."); }, onError: (error) => toast.error(error.message) });
  const entries = useMemo(() => active === "profile" ? (content.data ? [content.data as Entry] : []) : (Array.isArray(content.data) ? content.data as Entry[] : []), [active, content.data]);
  const editor = selected ?? entries[0] ?? (active === "profile" ? null : emptyItem[active]); const mediaProjects = (projectsForMedia.data ?? []) as Array<{ id: number; title: string }>; const projectMedia = ((allMedia.data ?? []) as Entry[]).filter((media) => media.projectId === selected?.id);
  const changeActive = (section: Section) => { setActive(section); setSelected(null); }; const updateField = (field: string, value: unknown) => setSelected({ ...(editor ?? {}), [field]: value }); const handleSave = () => editor && save.mutate({ type: active as any, data: editor as any });
  const handleFile = (file: File, target: "profile" | "project" | "icon" = "project", offset = 0) => { const reader = new FileReader(); reader.onload = () => { const base64 = String(reader.result); const mimeType = file.type || (file.name.toLowerCase().endsWith(".svg") ? "image/svg+xml" : ""); if (target === "profile") uploadProfilePhoto.mutate({ filename: file.name, mimeType, base64 }); else if (target === "icon") uploadSectionIcon.mutate({ filename: file.name, mimeType, base64 }); else if (editor?.id) uploadProjectImage.mutate({ projectId: editor.id, filename: file.name, mimeType, base64, alt: `${editor.title} image`, sortOrder: projectMedia.length + offset }); else toast.error("Save the project before uploading its images."); }; reader.readAsDataURL(file); };
  if (loading) return <div className="page-loading">LOADING ADMIN</div>;
  return <DashboardLayout>{user?.role !== "admin" ? <div className="permission-note"><h2>Administrator access required</h2><p>Sign in with the site owner account to manage portfolio content.</p></div> : <div>
    <div className="admin-head"><div><p className="section-index">CONTENT MANAGEMENT</p><h1>Portfolio control room</h1><p>Manage every part of the portfolio. Images are stored securely in S3, and all current content is editable.</p></div></div>
    <div className="admin-tabs">{sections.map(([key, label]) => <button className={`admin-tab ${active === key ? "active" : ""}`} onClick={() => changeActive(key)} key={key}>{label}</button>)}</div>
    <div className="admin-grid"><aside className="admin-list"><div className="admin-panel-title"><strong>Items</strong>{active !== "profile" && <button className="text-button" onClick={() => setSelected(emptyItem[active])}>+ Add item</button>}</div>{content.isLoading ? <div className="admin-row">Loading…</div> : entries.map((item) => <button className={`admin-row ${editor?.id === item.id ? "active" : ""}`} onClick={() => setSelected(item)} key={item.id}><strong>{displayTitle(active, item)}</strong><span>{item.status || item.category || item.organization || item.location || ""}</span></button>)}</aside>
      <section className="admin-editor"><div className="admin-panel-title"><strong>{editor?.id ? "Edit item" : "Add item"}</strong></div>{editor ? <div className="editor-form"><div className="field-grid">{fields[active].map((field) => { const value = editor[field]; const multiline = ["bio", "description", "summary", "details", "highlights", "tags", "tools", "outcomes", "keywords"].includes(field); const isBoolean = field === "featured" || field === "isCurrent"; if (isBoolean) return <label className="checkbox-field field full" key={field}><input type="checkbox" checked={!!value} onChange={(e) => updateField(field, e.target.checked)} />{labels[field]}</label>; if (field === "projectId") return <label className="field" key={field}><span>{labels[field]}</span><select value={value || ""} onChange={(e) => updateField(field, Number(e.target.value))}><option value="">Choose a project</option>{mediaProjects.map((project) => <option value={project.id} key={project.id}>{project.title}</option>)}</select></label>; if (field === "sectionKey" && active === "icons") return <label className="field" key={field}><span>{labels[field]}</span><select value={value || "education"} onChange={(e) => updateField(field, e.target.value)}><option value="education">Education</option><option value="publications">Publications</option><option value="experiences">Experience</option><option value="skills">Skills</option><option value="projects">Projects</option></select></label>; if (field === "icon" && active === "skills") return <label className="field" key={field}><span>{labels[field]}</span><select value={value || "ROS"} onChange={(e) => updateField(field, e.target.value)}><option value="ROS">ROS</option><option value="LiDAR">LiDAR / Navigation</option><option value="NVIDIA">NVIDIA / Edge AI</option><option value="Pixhawk">Embedded / Electronics</option><option value="OpenCV">OpenCV / Vision</option><option value="MATLAB">MATLAB / Control</option><option value="SolidWorks">CAD / Fabrication</option><option value="Python">Python / Software</option><option value="Cplusplus">C++</option></select></label>; const printable = Array.isArray(value) ? value.join("\n") : value ?? ""; return <label className={`field ${multiline ? "full" : ""}`} key={field}><span>{labels[field]}</span>{multiline ? <textarea value={printable} onChange={(e) => updateField(field, ["highlights", "tags", "tools", "outcomes", "keywords"].includes(field) ? e.target.value.split("\n").filter(Boolean) : e.target.value)} /> : <input type={field === "sortOrder" ? "number" : "text"} value={printable} onChange={(e) => updateField(field, field === "sortOrder" ? Number(e.target.value) : e.target.value)} />}</label>; })}</div>
      {active === "profile" && <div className="upload-box"><p>Upload a profile image from your device. It will be stored in S3 and applied automatically to your public profile.</p><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => event.target.files && Array.from(event.target.files).forEach((file) => handleFile(file, "profile"))} /></div>}
      {active === "icons" && <><div className="upload-box"><p>Upload an SVG, PNG, JPG, or WebP icon. Choose its section and display order, then save the item to publish it.</p><input type="file" accept="image/svg+xml,.svg,image/jpeg,image/png,image/webp" onChange={(event) => event.target.files && Array.from(event.target.files).forEach((file) => handleFile(file, "icon"))} /></div>{editor.url && <div className="media-manager"><p className="media-manager-title">Icon preview</p><div className="media-thumb icon-thumb"><img src={editor.url} alt={editor.alt || editor.label || "Section icon"} /></div></div>}</>}
      {active === "projects" && <><div className="upload-box"><p>Select multiple project images at once. Each image is stored in S3 and appears in the project gallery.</p><input type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif" onChange={(event) => event.target.files && Array.from(event.target.files).forEach((file, index) => handleFile(file, "project", index))} /></div>{editor?.id && <div className="media-manager"><p className="media-manager-title">Project images ({projectMedia.length})</p><div className="media-thumb-grid">{projectMedia.map((media) => <div className="media-thumb" key={media.id}><img src={media.url} alt={media.alt || "Project media"} /><button type="button" onClick={() => removeMedia.mutate({ type: "media", id: media.id })}>Delete</button></div>)}</div></div>}</>}
      <div className="editor-actions"><button className="button-primary" onClick={handleSave} disabled={save.isPending}>{save.isPending ? "Saving…" : "Save changes"}</button>{active !== "profile" && editor.id && <button className="danger-button" onClick={() => { if (window.confirm("Delete this item?")) remove.mutate({ type: active as Exclude<Section, "profile">, id: editor.id }); }}>Delete</button>}</div></div> : <div className="editor-form">Select an item or add a new one.</div>}</section>
    </div></div>}</DashboardLayout>;
}
