import { ArrowDownRight, ArrowUpRight, AtSign, ChevronRight, ExternalLink, Layers3, Settings, Sparkles } from "lucide-react";
import { useEffect } from "react";
import { SiArduino, SiNvidia, SiOpencv, SiPython, SiRos } from "react-icons/si";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";

const navItems = [["About", "#about"], ["Education", "#education"], ["Publications", "#publications"], ["Experience", "#experience"], ["Skills", "#skills"], ["Projects", "#projects"]];
const categoryPalette: Record<string, { accent: string; icon: React.ReactNode }> = {
  "Robotics Middleware": { accent: "blue", icon: <SiRos /> }, "Autonomy & Navigation": { accent: "sky", icon: <Layers3 /> }, "Embedded & Edge AI": { accent: "green", icon: <SiNvidia /> }, "Perception & AI": { accent: "violet", icon: <SiOpencv /> }, "Control & Simulation": { accent: "orange", icon: <Sparkles /> }, "Mechanical Design & CAD": { accent: "red", icon: <Layers3 /> }, "Electronics & PCB": { accent: "teal", icon: <SiArduino /> }, "Software & Data": { accent: "yellow", icon: <SiPython /> }, "Fabrication & Testing": { accent: "ink", icon: <Layers3 /> },
};

type MotifKind = "education" | "research" | "experience" | "skills" | "projects";

function BlueprintMotif({ kind }: { kind: MotifKind }) {
  const art = {
    education: <><path d="M18 40H342M18 100H342M18 160H342M18 220H342M70 18V242M150 18V242M230 18V242M310 18V242" /><path d="M116 84l64-38 64 38v76l-64 38-64-38zM116 84l64 38 64-38M180 122v76" /><circle cx="116" cy="84" r="5" /><circle cx="244" cy="84" r="5" /><circle cx="180" cy="198" r="5" /></>,
    research: <><path d="M28 202H334M56 32V222" /><path d="M56 176C98 152 105 116 143 126s52-68 93-61 50 37 98-18" /><path d="M56 196C98 171 105 139 143 149s52-68 93-61 50 37 98-18" /><path d="M56 156C98 132 105 96 143 106s52-68 93-61 50 37 98-18" /><circle cx="143" cy="126" r="7" /><circle cx="236" cy="65" r="7" /><circle cx="334" cy="47" r="7" /></>,
    experience: <><path d="M42 208H316M78 208V158L146 108l57 46 78-78" /><path d="M84 158l34 36M146 108l42 20M203 154l27 28" /><circle cx="78" cy="158" r="14" /><circle cx="146" cy="108" r="14" /><circle cx="203" cy="154" r="14" /><circle cx="281" cy="76" r="14" /><path d="M42 224h272M42 192h272" /></>,
    skills: <><rect x="92" y="62" width="176" height="136" rx="6" /><path d="M92 88H52M92 120H36M92 152H52M92 184H36M268 88h40M268 120h56M268 152h40M268 184h56M132 62V28M180 62V14M228 62V28M132 198v34M180 198v48M228 198v34" /><path d="M124 96h112v68H124zM142 114h76v32h-76z" /><circle cx="52" cy="88" r="4" /><circle cx="36" cy="120" r="4" /><circle cx="324" cy="120" r="4" /><circle cx="228" cy="28" r="4" /></>,
    projects: <><path d="M54 194L180 222l126-28V72L180 38 54 72zM54 72l126 38 126-38M180 110v112M86 86v78M274 86v78" /><path d="M22 230h316M34 40h292M22 224v14M338 224v14M34 32v16M326 32v16" /><circle cx="54" cy="72" r="5" /><circle cx="306" cy="72" r="5" /><circle cx="180" cy="222" r="5" /></>,
  } as const;
  return <div className={`section-motif motif-${kind}`} aria-hidden="true"><svg viewBox="0 0 360 260" fill="none">{art[kind]}</svg></div>;
}

export default function Home() {
  const { data, isLoading, error } = trpc.portfolio.public.useQuery();
  useEffect(() => {
    if (isLoading || !data?.profile) return;
    const sections = Array.from(document.querySelectorAll<HTMLElement>(".site-english [data-reveal]"));
    if (!("IntersectionObserver" in window)) { sections.forEach((section) => section.classList.add("is-revealed")); return; }
    const observer = new IntersectionObserver((entries) => entries.forEach(({ target, isIntersecting }) => target.classList.toggle("is-revealed", isIntersecting)), { threshold: 0.18, rootMargin: "0px 0px -10% 0px" });
    sections.forEach((section) => observer.observe(section));
    return () => observer.disconnect();
  }, [data?.profile?.id, isLoading]);
  if (isLoading) return <div className="page-loading">LOADING PORTFOLIO</div>;
  if (error || !data?.profile) return <div className="page-loading">Unable to load portfolio content.</div>;
  const profile = data.profile;
  const skillGroups = data.skills.reduce((groups, skill) => { (groups[skill.category] ??= []).push(skill); return groups; }, {} as Record<string, typeof data.skills>);
  return <div className="site-shell site-english">
    <header className="site-header"><div className="shell header-inner"><a className="wordmark" href="#about">{profile.name}</a><nav className="site-nav" aria-label="Primary navigation">{navItems.map(([label, href]) => <a key={href} href={href}>{label}</a>)}<Link className="nav-admin" href="/admin"><Settings size={13} /> Manage</Link></nav></div></header>
    <main>
      <section className="hero hero-english" id="about"><div className="shell hero-grid"><div><p className="eyebrow">Academic & Professional Portfolio</p><h1>Engineering <span>autonomous systems</span> that work in the real world.</h1><p className="hero-copy">{profile.bio}</p><div className="hero-actions"><a className="button-primary" href="#projects">Explore projects <ArrowDownRight size={16} /></a><a className="button-secondary" href={`mailto:${profile.email}`}><AtSign size={16} /> Get in touch</a></div><div className="hero-signal-row"><span>ROBOTICS</span><span>EMBEDDED</span><span>PERCEPTION</span><span>CONTROL</span></div></div><div className="hero-visual"><div className="portrait-frame">{profile.photoUrl ? <img src={profile.photoUrl} alt={profile.name} /> : <div className="portrait-placeholder"><span className="initials">MB</span><span className="portrait-note">PROFILE PHOTO · ADD FROM MANAGE</span></div>}</div><div className="coordinate-card"><p>FIELD / AUTONOMY</p><strong>{profile.professionalTitle}</strong><p>01 · 2026</p></div></div></div></section>
      <section className="section section--education" id="education" data-reveal><BlueprintMotif kind="education" /><div className="shell"><div className="section-head"><p className="section-index">01 / EDUCATION</p><div><h2 className="section-heading">Academic foundation</h2><p className="section-description">An interdisciplinary engineering foundation across mechanical design, electronics, control, and software for intelligent machines.</p></div></div>{data.education.map((item) => <article className="education-card" key={item.id}><div><span className="meta">{item.startYear} — {item.endYear}</span><h3>{item.degree} in {item.field}</h3><p className="experience-org">{item.institution} · {item.location}</p></div><p className="education-detail">{item.description}</p></article>)}</div></section>
      <section className="section section--publications" id="publications" data-reveal><BlueprintMotif kind="research" /><div className="shell"><div className="section-head"><p className="section-index">02 / PUBLICATIONS</p><div><h2 className="section-heading">Research & publications</h2><p className="section-description">Research focused on three-dimensional mapping, autonomous aerial systems, and resilient positioning in GPS-denied environments.</p></div></div><div className="publication-grid">{data.publications.map((item) => <Link className="publication-card publication-link" href={`/publications/${item.id}`} key={item.id}><span className="meta">{item.venue}</span><h3>{item.title}</h3><p>{item.summary}</p><div className="publication-footer"><span className="status-chip">{item.status} · {item.publicationDate}</span><span className="publication-open">View paper <ExternalLink size={13} /></span></div></Link>)}</div></div></section>
      <section className="section section--experience" id="experience" data-reveal><BlueprintMotif kind="experience" /><div className="shell"><div className="section-head"><p className="section-index">03 / EXPERIENCE</p><div><h2 className="section-heading">Research experience</h2><p className="section-description">Applied research across robotic platforms, field validation, sensing integration, and edge computing.</p></div></div><div className="experience-list">{data.experiences.map((item) => <article className="experience-item" key={item.id}><div><span className="meta">{item.startDate} — {item.endDate}</span><p className="experience-org">{item.organization}</p></div><div><h3 className="experience-role">{item.role}</h3><p className="experience-summary">{item.summary}</p><ul className="highlight-list">{item.highlights.map((highlight, index) => <li key={index}>{highlight}</li>)}</ul></div></article>)}</div></div></section>
      <section className="section skills-section" id="skills" data-reveal><BlueprintMotif kind="skills" /><div className="shell"><div className="skills-heading-row"><div><p className="section-index">04 / TECHNICAL CAPABILITIES</p><h2 className="section-heading">Skills, organised by <span>system layer.</span></h2></div><p className="section-description">A technical skills map across robotics, embedded systems, autonomy, design, electronics, software, and fabrication.</p></div><div className="skills-overview"><div><span className="skills-kicker">CAPABILITY MAP</span><strong>{data.skills.length}</strong><p>skills available to curate</p></div><div className="skills-overview-line" /><div><span className="skills-kicker">DISCIPLINES</span><strong>{Object.keys(skillGroups).length}</strong><p>connected engineering layers</p></div></div><div className="skill-category-grid">{Object.entries(skillGroups).map(([category, skills]) => { const theme = categoryPalette[category] ?? { accent: "teal", icon: <Sparkles /> }; return <article className={`skill-category-card ${theme.accent}`} key={category}><div className="skill-category-top"><span className="skill-category-icon">{theme.icon}</span><span className="skill-count">{skills.length.toString().padStart(2, "0")}</span></div><h3>{category}</h3><div className="skill-pill-list">{skills.map((skill) => <span key={skill.id}>{skill.label}<ChevronRight size={12} /></span>)}</div></article>; })}</div></div></section>
      <section className="section section--projects" id="projects" data-reveal><BlueprintMotif kind="projects" /><div className="shell"><div className="project-intro"><div><p className="section-index">05 / PROJECT ARCHIVE</p><h2 className="section-heading">Selected work, <span>fully documented.</span></h2></div><p>Each project opens as a focused case study with its context, system stack, key outcomes, and image gallery.</p></div><div className="project-grid">{data.projects.map((project) => <Link className="project-card" href={`/projects/${project.slug}`} key={project.id}><span className="project-arrow"><ArrowUpRight size={19} /></span>{project.media[0] ? <img className="project-image" src={project.media[0].url} alt={project.media[0].alt ?? project.title} /> : <div className="project-image-fallback" />}<div className="project-body"><span className="meta">{project.status}</span><h3>{project.title}</h3><p>{project.summary}</p><div className="tag-list">{project.tags.slice(0, 4).map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div></div></Link>)}</div></div></section>
    </main><footer className="footer"><div className="shell footer-inner"><span>© {new Date().getFullYear()} {profile.name}</span><a className="footer-contact" href={`mailto:${profile.email}`}>{profile.email} <ArrowUpRight size={13} /></a></div></footer>
  </div>;
}
