import { ArrowDownRight, ArrowUpRight, AtSign, ChevronRight, ExternalLink, Layers3, Settings, Sparkles } from "lucide-react";
import { useEffect } from "react";
import { SiArduino, SiNvidia, SiOpencv, SiPython, SiRos } from "react-icons/si";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";

const navItems = [["About", "#about"], ["Education", "#education"], ["Publications", "#publications"], ["Experience", "#experience"], ["Skills", "#skills"], ["Projects", "#projects"]];
const categoryPalette: Record<string, { accent: string; icon: React.ReactNode }> = {
  "Robotics Middleware": { accent: "blue", icon: <SiRos /> }, "Autonomy & Navigation": { accent: "sky", icon: <Layers3 /> }, "Embedded & Edge AI": { accent: "green", icon: <SiNvidia /> }, "Perception & AI": { accent: "violet", icon: <SiOpencv /> }, "Control & Simulation": { accent: "orange", icon: <Sparkles /> }, "Mechanical Design & CAD": { accent: "red", icon: <Layers3 /> }, "Electronics & PCB": { accent: "teal", icon: <SiArduino /> }, "Software & Data": { accent: "yellow", icon: <SiPython /> }, "Fabrication & Testing": { accent: "ink", icon: <Layers3 /> },
};

type SectionKey = "education" | "publications" | "experiences" | "skills" | "projects";
type ManagedIcon = { id: number; sectionKey: string; url: string; alt: string | null; sortOrder: number };

function SectionSymbol({ sectionKey, icons, className }: { sectionKey: SectionKey; icons: ManagedIcon[]; className: string }) {
  const sectionIcons = icons.filter((icon) => icon.sectionKey === sectionKey);
  if (!sectionIcons.length) return null;
  return <div className={`section-symbol ${sectionIcons.length > 1 ? "section-symbol--automation" : ""} ${className}`} aria-hidden="true">{sectionIcons.map((icon) => <img key={icon.id} src={icon.url} alt="" />)}</div>;
}

export default function Home() {
  const { data, isLoading, error } = trpc.portfolio.public.useQuery();
  useEffect(() => {
    if (isLoading || !data?.profile) return;
    const sections = Array.from(document.querySelectorAll<HTMLElement>(".site-english [data-reveal]"));
    if (!("IntersectionObserver" in window)) { sections.forEach((section) => section.classList.add("is-revealed")); return; }
    const observer = new IntersectionObserver((entries) => entries.forEach(({ target, isIntersecting }) => target.classList.toggle("is-revealed", isIntersecting)), { threshold: 0.18, rootMargin: "0px 0px -10% 0px" });
    sections.forEach((section) => observer.observe(section));
    return () => observer.disconnect();
  }, [data?.profile?.id, isLoading]);
  if (isLoading) return <div className="page-loading">LOADING PORTFOLIO</div>;
  if (error || !data?.profile) return <div className="page-loading">Unable to load portfolio content.</div>;
  const profile = data.profile;
  const sectionIcons = (data.sectionIcons ?? []) as ManagedIcon[];
  const skillGroups = data.skills.reduce((groups, skill) => { (groups[skill.category] ??= []).push(skill); return groups; }, {} as Record<string, typeof data.skills>);
  return <div className="site-shell site-english">
    <header className="site-header"><div className="shell header-inner"><a className="wordmark" href="#about">{profile.name}</a><nav className="site-nav" aria-label="Primary navigation">{navItems.map(([label, href]) => <a key={href} href={href}>{label}</a>)}<Link className="nav-services" href="/services">Services</Link><Link className="nav-admin" href="/admin"><Settings size={13} /> Manage</Link></nav></div></header>
    <main>
      <section className="hero hero-english" id="about"><div className="shell hero-grid"><div><p className="eyebrow">Academic & Professional Portfolio</p><h1>Engineering <span>autonomous systems</span> that work in the real world.</h1><p className="hero-copy">{profile.bio}</p><div className="hero-actions"><a className="button-primary" href="#projects">Explore projects <ArrowDownRight size={16} /></a><Link className="button-secondary" href="/services">View engineering services <ArrowUpRight size={16} /></Link><a className="button-secondary" href={`mailto:${profile.email}`}><AtSign size={16} /> Get in touch</a></div><div className="hero-signal-row"><span>ROBOTICS</span><span>EMBEDDED</span><span>PERCEPTION</span><span>CONTROL</span></div></div><div className="hero-visual"><div className="portrait-frame">{profile.photoUrl ? <img src={profile.photoUrl} alt={profile.name} /> : <div className="portrait-placeholder"><span className="initials">MB</span><span className="portrait-note">PROFILE PHOTO · ADD FROM MANAGE</span></div>}</div><div className="coordinate-card"><p>FIELD / AUTONOMY</p><strong>{profile.professionalTitle}</strong><p>01 · 2026</p></div></div></div></section>
      <section className="section section--education" id="education" data-reveal><SectionSymbol sectionKey="education" icons={sectionIcons} className="symbol-education" /><div className="shell"><div className="section-head"><p className="section-index">01 / EDUCATION</p><div><h2 className="section-heading">Academic foundation</h2><p className="section-description">An interdisciplinary engineering foundation across mechanical design, electronics, control, and software for intelligent machines.</p></div></div>{data.education.map((item) => <article className="education-card" key={item.id}><div><span className="meta">{item.startYear} — {item.endYear}</span><h3>{item.degree} in {item.field}</h3><p className="experience-org">{item.institution} · {item.location}</p></div><p className="education-detail">{item.description}</p></article>)}</div></section>
      <section className="section section--publications" id="publications" data-reveal><SectionSymbol sectionKey="publications" icons={sectionIcons} className="symbol-publications" /><div className="shell"><div className="section-head"><p className="section-index">02 / PUBLICATIONS</p><div><h2 className="section-heading">Research & publications</h2><p className="section-description">Research focused on three-dimensional mapping, autonomous aerial systems, and resilient positioning in GPS-denied environments.</p></div></div><div className="publication-grid">{data.publications.map((item) => <Link className="publication-card publication-link" href={`/publications/${item.id}`} key={item.id}><span className="meta">{item.venue}</span><h3>{item.title}</h3><p>{item.summary}</p><div className="publication-footer"><span className="status-chip">{item.status} · {item.publicationDate}</span><span className="publication-open">View paper <ExternalLink size={13} /></span></div></Link>)}</div></div></section>
      <section className="section section--experience" id="experience" data-reveal><SectionSymbol sectionKey="experiences" icons={sectionIcons} className="symbol-experience" /><div className="shell"><div className="section-head"><p className="section-index">03 / EXPERIENCE</p><div><h2 className="section-heading">Research experience</h2><p className="section-description">Applied research across robotic platforms, field validation, sensing integration, and edge computing.</p></div></div><div className="experience-list">{data.experiences.map((item) => <article className="experience-item" key={item.id}><div><span className="meta">{item.startDate} — {item.endDate}</span><p className="experience-org">{item.organization}</p></div><div><h3 className="experience-role">{item.role}</h3><p className="experience-summary">{item.summary}</p><ul className="highlight-list">{item.highlights.map((highlight, index) => <li key={index}>{highlight}</li>)}</ul></div></article>)}</div></div></section>
      <section className="section skills-section" id="skills" data-reveal><SectionSymbol sectionKey="skills" icons={sectionIcons} className="symbol-skills" /><div className="shell"><div className="skills-heading-row"><div><p className="section-index">04 / TECHNICAL CAPABILITIES</p><h2 className="section-heading">Skills, organised by <span>system layer.</span></h2></div><p className="section-description">A technical skills map across robotics, embedded systems, autonomy, design, electronics, software, and fabrication.</p></div><div className="skills-overview"><div><span className="skills-kicker">CAPABILITY MAP</span><strong>{data.skills.length}</strong><p>skills available to curate</p></div><div className="skills-overview-line" /><div><span className="skills-kicker">DISCIPLINES</span><strong>{Object.keys(skillGroups).length}</strong><p>connected engineering layers</p></div></div><div className="skill-category-grid">{Object.entries(skillGroups).map(([category, skills]) => { const theme = categoryPalette[category] ?? { accent: "teal", icon: <Sparkles /> }; return <article className={`skill-category-card ${theme.accent}`} key={category}><div className="skill-category-top"><span className="skill-category-icon">{theme.icon}</span><span className="skill-count">{skills.length.toString().padStart(2, "0")}</span></div><h3>{category}</h3><div className="skill-pill-list">{skills.map((skill) => <span key={skill.id}>{skill.label}<ChevronRight size={12} /></span>)}</div></article>; })}</div></div></section>
      <section className="section section--projects" id="projects" data-reveal><SectionSymbol sectionKey="projects" icons={sectionIcons} className="symbol-projects" /><div className="shell"><div className="project-intro"><div><p className="section-index">05 / PROJECT ARCHIVE</p><h2 className="section-heading">Selected work, <span>fully documented.</span></h2></div><p>Each project opens as a focused case study with its context, system stack, key outcomes, and image gallery.</p></div><div className="project-grid">{data.projects.map((project) => <Link className="project-card" href={`/projects/${project.slug}`} key={project.id}><span className="project-arrow"><ArrowUpRight size={19} /></span>{project.media[0] ? <img className="project-image" src={project.media[0].url} alt={project.media[0].alt ?? project.title} /> : <div className="project-image-fallback" />}<div className="project-body"><span className="meta">{project.status}</span><h3>{project.title}</h3><p>{project.summary}</p><div className="tag-list">{project.tags.slice(0, 4).map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div></div></Link>)}</div></div></section>
    </main><footer className="footer"><div className="shell footer-inner"><span>© {new Date().getFullYear()} {profile.name}</span><span className="icon-credit">Industrial icons by <a href="https://www.streamlinehq.com/" target="_blank" rel="noreferrer">Streamline</a> · CC BY 4.0</span><a className="footer-contact" href={`mailto:${profile.email}`}>{profile.email} <ArrowUpRight size={13} /></a></div></footer>
  </div>;
}
