import { ArrowLeft, CalendarDays, Images, Wrench } from "lucide-react";
import { Link, useParams } from "wouter";
import { trpc } from "@/lib/trpc";

export default function ProjectDetail() {
  const { slug } = useParams<{ slug: string }>(); const { data, isLoading } = trpc.portfolio.public.useQuery();
  if (isLoading) return <div className="page-loading">LOADING PROJECT</div>;
  const project = data?.projects.find((item) => item.slug === slug); if (!project) return <div className="page-loading">Project not found.</div>;
  return <div className="site-shell site-english"><header className="site-header"><div className="shell header-inner"><Link className="wordmark" href="/"><span className="wordmark-mark">MB</span><span>Mohammed Bajhaw</span></Link><Link className="nav-admin" href="/">Home <ArrowLeft size={13} /></Link></div></header><main className="project-detail"><div className="shell"><Link className="project-back" href="/"><ArrowLeft size={16} /> Back to all projects</Link><section className="project-detail-hero"><div><p className="eyebrow">{project.subtitle}</p><h1>{project.title}</h1><p className="project-detail-summary">{project.summary}</p></div><div className="project-detail-meta"><div><span>Status</span><strong>{project.status}</strong></div><div><span>Timeline</span><strong>{project.startDate} — {project.endDate}</strong></div><div><span>Focus</span><strong>{project.tags[0]}</strong></div></div></section><section className={`project-gallery ${project.media.length > 1 ? "gallery-multiple" : ""}`}>{project.media.length ? project.media.map((media, index) => <figure key={media.id}><img src={media.url} alt={media.alt ?? project.title} />{index === 0 && project.media.length > 1 && <figcaption><Images size={14} /> {project.media.length} project images</figcaption>}</figure>) : <div className="gallery-placeholder" />}</section><section className="project-content"><aside className="detail-aside"><div className="detail-block"><h3><Wrench size={14} /> Tools & stack</h3><ul className="plain-list">{project.tools.map((tool) => <li key={tool}>{tool}</li>)}</ul></div><div className="detail-block"><h3><CalendarDays size={14} /> Key outcomes</h3><ul className="plain-list">{project.outcomes.map((outcome) => <li key={outcome}>{outcome}</li>)}</ul></div></aside><div><h2>Project overview</h2><p className="project-copy">{project.description}</p><div className="tag-list project-detail-tags">{project.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div></div></section></div></main></div>;
}
