import { ArrowLeft, ExternalLink, FileText, UsersRound } from "lucide-react";
import { Link, useParams } from "wouter";
import { trpc } from "@/lib/trpc";

export default function PublicationDetail() {
  const { id } = useParams<{ id: string }>(); const { data, isLoading } = trpc.portfolio.public.useQuery();
  if (isLoading) return <div className="page-loading">LOADING PUBLICATION</div>;
  const publication = data?.publications.find((item) => item.id === Number(id)); if (!publication) return <div className="page-loading">Publication not found.</div>;
  return <div className="site-shell site-english"><header className="site-header"><div className="shell header-inner"><Link className="wordmark" href="/"><span className="wordmark-mark">MB</span><span>Mohammed Bajhaw</span></Link><Link className="nav-admin" href="/">Home <ArrowLeft size={13} /></Link></div></header><main className="publication-detail"><div className="shell"><Link className="project-back" href="/"><ArrowLeft size={16} /> Back to publications</Link><section className="publication-detail-hero"><p className="eyebrow">{publication.venue}</p><h1>{publication.title}</h1><div className="publication-meta-grid"><div><span>Publication status</span><strong>{publication.status}</strong></div><div><span>Conference / venue</span><strong>{publication.venue}</strong></div><div><span>Publication date</span><strong>{publication.publicationDate}</strong></div><div><span>Authors</span><strong>{publication.authors}</strong></div></div></section><section className="publication-content"><div className="paper-main"><div className="paper-section"><span className="paper-label">Abstract</span><h2>Research abstract</h2><p>{publication.summary}</p></div><div className="paper-section"><span className="paper-label">Paper details</span><h2>Research context</h2><p>{publication.details || "Add the methodology, results, and approved publication details from the management page."}</p></div><div className="paper-section"><span className="paper-label">Keywords</span><h2>Key topics</h2><div className="keyword-list">{publication.keywords.map((keyword) => <span key={keyword}>{keyword}</span>)}</div></div></div><aside className="paper-side"><div className="paper-authors"><UsersRound size={18} /><h3>Contributors</h3><p>{publication.authors || "Add contributors from Manage"}</p></div><div className="paper-pdf"><FileText size={20} /><h3>Paper PDF</h3><p>{publication.url ? "The paper is available to open or download." : "Add an official PDF or permitted preprint URL from Manage."}</p>{publication.url ? <a className="button-primary" href={publication.url} target="_blank" rel="noreferrer">Open PDF <ExternalLink size={15} /></a> : <span className="button-secondary is-disabled">PDF link pending</span>}</div></aside></section></div></main></div>;
}
