export const portfolioSeed = {
  profile: {
    id: 1,
    name: "Mohammed Bajhaw",
    professionalTitle: "Mechatronics Engineering Researcher · Autonomous Systems & Robotics",
    location: "Elazığ, Türkiye",
    email: "mohammedbajhaw2020@gmail.com",
    linkedinUrl: "https://linkedin.com/in/mohammedbajhaw",
    bio: "باحث ومهندس ميكاترونكس مهتم بالأنظمة الذاتية والروبوتات والأنظمة المضمنة. أعمل على دمج الاستشعار المتقدم، خوارزميات SLAM، والذكاء الاصطناعي لبناء منصات روبوتية قابلة للتطبيق في البيئات الواقعية.",
    photoUrl: null,
    photoKey: null,
  },
  education: [
    {
      institution: "Fırat University",
      degree: "Bachelor’s Degree",
      field: "Mechatronics Engineering",
      location: "Elazığ, Türkiye",
      startYear: "2021",
      endYear: "2026",
      description: "دراسة هندسة الميكاترونكس مع تركيز أكاديمي ومشاريع تطبيقية في الروبوتات والأنظمة الذاتية والأنظمة المضمنة.",
      sortOrder: 1,
    },
  ],
  publications: [
    {
      title: "Drift-Resilient Indoor 3D Mapping in GPS-Denied Environments Using RKO-LIO with Velodyne–Pixhawk Integration in ROS 2",
      venue: "ICHORA 2026 · IEEE Conference",
      publicationDate: "May 2026",
      status: "Accepted & Published",
      authors: "Co-author",
      summary: "بحث عن حل متين للتموضع ورسم الخرائط ثلاثية الأبعاد في البيئات الداخلية المحرومة من GPS باستخدام ROS 2 وتكامل Velodyne وPixhawk.",
      url: null,
      sortOrder: 1,
    },
    {
      title: "Demonstrating the Efficiency of RKO-LIO on a DJI UAV Platform Utilizing Drone Built-in IMU for GPS-Denied Mapping",
      venue: "Research Paper",
      publicationDate: "2026",
      status: "Research Paper",
      authors: "First author",
      summary: "إطار تكامل عتادي وبرمجي للطائرات المسيّرة يعمل في بيئات محرومة من GPS باستخدام IMU المدمج وخوارزميات LiDAR SLAM.",
      url: null,
      sortOrder: 2,
    },
  ],
  experiences: [
    {
      role: "Volunteer Researcher",
      organization: "RAI Laboratory, Fırat University",
      location: "Elazığ, Türkiye",
      startDate: "Sep 2025",
      endDate: "Present",
      isCurrent: true,
      summary: "بحث وتطوير في إدارة الكوارث الذاتية بالاعتماد على روبوتات متغايرة ضمن مشروع TÜBİTAK 1001.",
      highlights: [
        "اختبار خوارزميات SLAM في بيئات محرومة من GPS وإدارة عمليات الملاحة والتحكم للطائرات المسيّرة.",
        "جمع بيانات ميدانية ودعم تصميم نماذج CAD ثلاثية الأبعاد لتركيب الحساسات.",
        "المساهمة الفنية في إعداد ونشر أبحاث أكاديمية.",
      ],
      sortOrder: 1,
    },
    {
      role: "Robotics Research Intern",
      organization: "RAI Laboratory, Fırat University",
      location: "Elazığ, Türkiye",
      startDate: "Jul 2025",
      endDate: "Sep 2025",
      isCurrent: false,
      summary: "تكامل عتادي وبرمجي لطائرة DJI Matrice 350 RTK مع NVIDIA Jetson Orin NX.",
      highlights: [
        "اختبارات محاكاة وميدانية لخوارزميات SLAM باستخدام Velodyne LiDAR وكاميرات RealSense.",
        "دعم تكامل الاستشعار والحوسبة الطرفية لمنصات روبوتية جوية.",
      ],
      sortOrder: 2,
    },
  ],
  skills: [
    { label: "ROS 1 / ROS 2", category: "Autonomy", icon: "Radar", sortOrder: 1 },
    { label: "LiDAR SLAM", category: "Autonomy", icon: "ScanLine", sortOrder: 2 },
    { label: "NVIDIA Jetson", category: "Embedded", icon: "Cpu", sortOrder: 3 },
    { label: "Pixhawk & CAN-Bus", category: "Embedded", icon: "CircuitBoard", sortOrder: 4 },
    { label: "OpenCV & YOLO", category: "AI & Vision", icon: "Eye", sortOrder: 5 },
    { label: "MATLAB / Simulink", category: "Engineering", icon: "ChartNoAxesCombined", sortOrder: 6 },
    { label: "SolidWorks & CAD", category: "Engineering", icon: "Box", sortOrder: 7 },
    { label: "Python & C++", category: "Development", icon: "Code2", sortOrder: 8 },
  ],
  projects: [
    {
      slug: "advanced-robotics-research",
      title: "Advanced Robotics Research",
      subtitle: "TÜBİTAK 1001 · Autonomous Disaster Management",
      summary: "منصة بحثية تجمع طائرة DJI Matrice 350 RTK مع Jetson Orin NX وحساسات LiDAR وRealSense لرسم خرائط ثلاثية الأبعاد في بيئات محرومة من GPS.",
      description: "يستكشف هذا المشروع البنية العتادية والبرمجية اللازمة لروبوتات جوية تدعم عمليات إدارة الكوارث. تم دمج منصة طيران DJI Matrice 350 RTK مع وحدة NVIDIA Jetson Orin NX عبر DJI Payload SDK، وربطها بحساسات LiDAR وكاميرات Intel RealSense.\n\nيركز العمل على تطبيق خوارزميات SLAM عالية الدقة في بيئات لا تتوفر فيها إشارة GPS، مع بناء مسار اختبار من المحاكاة إلى التجارب الميدانية. كما ساهم المشروع في إنشاء مجموعة بيانات واسعة لتدريب نماذج اكتشاف الضحايا.",
      status: "Ongoing research",
      startDate: "Sep 2025",
      endDate: "Present",
      tags: ["Autonomous Systems", "ROS 2", "LiDAR SLAM", "UAVs"],
      tools: ["DJI Matrice 350 RTK", "NVIDIA Jetson Orin NX", "Velodyne LiDAR", "Intel RealSense", "ROS 2"],
      outcomes: ["رسم خرائط ثلاثية الأبعاد عالية الدقة في بيئات GPS-denied.", "تكامل DJI Payload SDK مع حوسبة طرفية وحساسات متعددة.", "المساهمة في إنشاء مجموعة بيانات من 18,000 صورة لاكتشاف الضحايا."],
      featured: true,
      sortOrder: 1,
    },
    {
      slug: "autonomous-medical-search-rescue-robot",
      title: "Autonomous Medical Search & Rescue Robot",
      subtitle: "TÜBİTAK 2209 · Multimodal Rescue Platform",
      summary: "منصة إنقاذ متعددة الحساسات تعمل على Jetson TX2 وتجمع الرؤية الحرارية وRGB وراداراً حيوياً وLoRa وواجهة صوتية محلية للإرشاد الأولي.",
      description: "منصة بحث وإنقاذ مستقلة صُممت للمساعدة في تحديد مؤشرات الحياة والظروف الخطرة في مواقع الكوارث. تعتمد على دمج بيانات كاميرات حرارية وRGB مع Bio-Radar، وتستخدم LoRa للاتصال بعيد المدى.\n\nيتضمن التصميم آليات Cognitive Override وWake-on-Suspect لتقليل استهلاك الطاقة، إلى جانب صوت محلي مدعوم بنموذج لغوي لتقديم إرشادات أولية قبل وصول فرق الإنقاذ.",
      status: "Ongoing research",
      startDate: "Feb 2026",
      endDate: "Present",
      tags: ["Search & Rescue", "Sensor Fusion", "Edge AI", "LoRa"],
      tools: ["NVIDIA Jetson TX2", "Thermal + RGB Cameras", "Bio-Radar", "LoRa", "Local LLM / TTS"],
      outcomes: ["تصميم بنية متعددة الحساسات للبحث عن الناجين.", "دمج تنبيه صحي أولي بواجهة صوتية محلية.", "تحسين استهلاك الطاقة باستخدام Wake-on-Suspect."],
      featured: true,
      sortOrder: 2,
    },
    {
      slug: "three-axis-robotic-arm",
      title: "3-Axis Robotic Arm Modeling & Control",
      subtitle: "Mechanical Design · Kinematics · PID Control",
      summary: "تصميم ميكانيكي وتحليل حركي لذراع روبوتية ثلاثية المحاور، مع محاكاة التحكم PID في MATLAB وSimulink قبل مرحلة الإنتاج.",
      description: "يجمع المشروع بين التصميم الميكانيكي والتحكم. تم تصميم الهيكل في SolidWorks، ثم تطوير نموذج للحركة وتحليل السينماتيكا للتحقق من نطاقات الحركة والدقة.\n\nقبل أي تصنيع، تم اختبار منطق التحكم PID في MATLAB وSimulink بهدف دراسة الاستجابة وتحسين الحركة الدقيقة عبر المحاور الثلاثة.",
      status: "Completed",
      startDate: "2024",
      endDate: "2024",
      tags: ["Robotics", "SolidWorks", "PID Control", "MATLAB"],
      tools: ["SolidWorks", "MATLAB", "Simulink", "PID Control"],
      outcomes: ["تصميم هيكل ثلاثي المحاور قابل للتصنيع.", "تحليل كينماتيكي لمجال الحركة.", "محاكاة منطق التحكم قبل الإنتاج."],
      featured: true,
      sortOrder: 3,
    },
    {
      slug: "smart-coffee-brewing-system",
      title: "Smart Coffee Brewing System",
      subtitle: "Raspberry Pi 5 · Automation · IoT",
      summary: "نظام تخمير قهوة مؤتمت يوضح تكامل الحوسبة المضمنة والتحكم والـ IoT باستخدام Raspberry Pi 5.",
      description: "مشروع تطبيقي في الأتمتة المنزلية يستخدم Raspberry Pi 5 لإدارة خطوات التخمير وربط الحساسات والمحركات في واجهة تحكم واحدة.",
      status: "Completed",
      startDate: "2024",
      endDate: "2024",
      tags: ["Raspberry Pi", "IoT", "Automation"],
      tools: ["Raspberry Pi 5", "Sensors", "IoT"],
      outcomes: ["إثبات تكامل العتاد والبرمجيات في نظام مؤتمت صغير."],
      featured: false,
      sortOrder: 4,
    },
    {
      slug: "high-precision-cnc-router",
      title: "High-Precision CNC Router",
      subtitle: "Digital Fabrication · CNC · Motion Systems",
      summary: "تحويل طابعة ثلاثية الأبعاد إلى راوتر CNC عالي الدقة للحفر على الخشب والبلاستيك.",
      description: "يستعرض المشروع إعادة توظيف منصة طباعة ثلاثية الأبعاد وتحويلها إلى نظام CNC للحفر مع تهيئة الميكانيكا والحركة والتحكم بما يناسب خامات الخشب والبلاستيك.",
      status: "Completed",
      startDate: "2024",
      endDate: "2024",
      tags: ["CNC", "CAD/CAM", "Digital Fabrication"],
      tools: ["CAD/CAM", "CNC Router", "Motion Control"],
      outcomes: ["منصة CNC عملية للحفر على الخشب والبلاستيك."],
      featured: false,
      sortOrder: 5,
    },
  ],
  media: [
    { slug: "advanced-robotics-research", url: "/manus-storage/lidar-uav-mapping_483e4614.jpg", alt: "طائرة مسيرة مع مستشعر LiDAR في بيئة اختبار", sortOrder: 1 },
    { slug: "autonomous-medical-search-rescue-robot", url: "/manus-storage/search-rescue-robot_b4ab7cbe.jpg", alt: "روبوت بحث وإنقاذ متعدد الحساسات", sortOrder: 1 },
    { slug: "three-axis-robotic-arm", url: "/manus-storage/robotic-arm-control_7d96276c.jpg", alt: "ذراع روبوتية ثلاثية المحاور", sortOrder: 1 },
  ],
};
