create extension if not exists pgcrypto;

create table public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_portfolio_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

create table public.profiles (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete set null,
  name text not null,
  professional_title text not null,
  location text,
  email text,
  linkedin_url text,
  phone text,
  bio text,
  photo_path text,
  photo_alt text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.education (
  id bigint generated by default as identity primary key,
  institution text not null,
  degree text not null,
  field text,
  location text,
  start_year text,
  end_year text,
  description text,
  sort_order integer not null default 0
);

create table public.publications (
  id bigint generated by default as identity primary key,
  title text not null,
  venue text,
  publication_date text,
  status text,
  authors text,
  summary text,
  details text,
  keywords text[] not null default '{}',
  url text,
  sort_order integer not null default 0
);

create table public.experiences (
  id bigint generated by default as identity primary key,
  role text not null,
  organization text not null,
  location text,
  start_date text,
  end_date text,
  is_current boolean not null default false,
  summary text,
  highlights text[] not null default '{}',
  sort_order integer not null default 0
);

create table public.skills (
  id bigint generated by default as identity primary key,
  label text not null,
  category text not null,
  icon text,
  sort_order integer not null default 0
);

create table public.section_icons (
  id bigint generated by default as identity primary key,
  section_key text not null,
  label text not null,
  storage_path text not null,
  alt text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.service_areas (
  id bigint generated by default as identity primary key,
  title text not null unique,
  description text,
  accent text not null default 'teal',
  icon text not null default 'robotics',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.services (
  id bigint generated by default as identity primary key,
  area_id bigint not null references public.service_areas(id) on delete cascade,
  title text not null,
  summary text,
  deliverables text[] not null default '{}',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (area_id, title)
);

create table public.projects (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  subtitle text,
  summary text,
  description text,
  status text,
  start_date text,
  end_date text,
  tags text[] not null default '{}',
  tools text[] not null default '{}',
  outcomes text[] not null default '{}',
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.project_media (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  storage_path text not null,
  alt text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger service_areas_set_updated_at before update on public.service_areas for each row execute function public.set_updated_at();
create trigger services_set_updated_at before update on public.services for each row execute function public.set_updated_at();
create trigger projects_set_updated_at before update on public.projects for each row execute function public.set_updated_at();

alter table public.admin_users enable row level security;
alter table public.profiles enable row level security;
alter table public.education enable row level security;
alter table public.publications enable row level security;
alter table public.experiences enable row level security;
alter table public.skills enable row level security;
alter table public.section_icons enable row level security;
alter table public.service_areas enable row level security;
alter table public.services enable row level security;
alter table public.projects enable row level security;
alter table public.project_media enable row level security;

create policy "admin_users_read_self" on public.admin_users for select to authenticated using (user_id = auth.uid());

create policy "profiles_public_read" on public.profiles for select to anon, authenticated using (true);
create policy "education_public_read" on public.education for select to anon, authenticated using (true);
create policy "publications_public_read" on public.publications for select to anon, authenticated using (true);
create policy "experiences_public_read" on public.experiences for select to anon, authenticated using (true);
create policy "skills_public_read" on public.skills for select to anon, authenticated using (true);
create policy "section_icons_public_read" on public.section_icons for select to anon, authenticated using (true);
create policy "service_areas_public_read" on public.service_areas for select to anon, authenticated using (true);
create policy "services_public_read" on public.services for select to anon, authenticated using (true);
create policy "projects_public_read" on public.projects for select to anon, authenticated using (true);
create policy "project_media_public_read" on public.project_media for select to anon, authenticated using (true);

create policy "profiles_admin_write" on public.profiles for all to authenticated using (public.is_portfolio_admin()) with check (public.is_portfolio_admin());
create policy "education_admin_write" on public.education for all to authenticated using (public.is_portfolio_admin()) with check (public.is_portfolio_admin());
create policy "publications_admin_write" on public.publications for all to authenticated using (public.is_portfolio_admin()) with check (public.is_portfolio_admin());
create policy "experiences_admin_write" on public.experiences for all to authenticated using (public.is_portfolio_admin()) with check (public.is_portfolio_admin());
create policy "skills_admin_write" on public.skills for all to authenticated using (public.is_portfolio_admin()) with check (public.is_portfolio_admin());
create policy "section_icons_admin_write" on public.section_icons for all to authenticated using (public.is_portfolio_admin()) with check (public.is_portfolio_admin());
create policy "service_areas_admin_write" on public.service_areas for all to authenticated using (public.is_portfolio_admin()) with check (public.is_portfolio_admin());
create policy "services_admin_write" on public.services for all to authenticated using (public.is_portfolio_admin()) with check (public.is_portfolio_admin());
create policy "projects_admin_write" on public.projects for all to authenticated using (public.is_portfolio_admin()) with check (public.is_portfolio_admin());
create policy "project_media_admin_write" on public.project_media for all to authenticated using (public.is_portfolio_admin()) with check (public.is_portfolio_admin());

insert into storage.buckets (id, name, public)
values ('portfolio-media', 'portfolio-media', true)
on conflict (id) do update set public = true;

create policy "portfolio_media_public_read" on storage.objects for select to anon, authenticated using (bucket_id = 'portfolio-media');
create policy "portfolio_media_admin_write" on storage.objects for all to authenticated using (bucket_id = 'portfolio-media' and public.is_portfolio_admin()) with check (bucket_id = 'portfolio-media' and public.is_portfolio_admin());
